### ISSUE TITLE
Turret weapon settings reset on respawn

### ISSUE THREAD

**Issue by RahlForge** [Raptor007/X-Wing-Revival#3]
When respawning, the weapon link resets back to single fire for both lasers and projectiles (so if you were set to dual- or quad-fire mode, you have to cycle back to that after respawn).

**Comment by Raptor007** [comment]
Done in v0.4 for ship pilots.  Turrets still start on their own default mode.

**Comment by Raptor007** [comment]
This is mostly done for turret gunners.  Preferred fire mode is now sent in the seat change packet.  Just need to make sure it is also applied when respawning as a turret gunner.
